"""CLI, TUI, and terminal interaction helpers for ellements."""

from .adapters import (
    guideline_provider_from_library,
    persona_provider_from_library,
)
from .agent_tui import (
    BUILTIN_COMMANDS,
    AgentRunner,
    AgentTUI,
    FileSaveHandler,
    GuidelineProvider,
    Mode,
    PersonaProvider,
    RunResult,
    SaveHandler,
    SlashCommand,
    TuiConfig,
    TuiControls,
    run_agent_tui,
)
from .components import (
    ISSUE_STYLES,
    ROLE_STYLES,
    app_header,
    chat_input_prompt,
    chat_message,
    error,
    issue_line,
    issues_block,
    key_value_table,
    result_json,
    result_markdown,
    section_rule,
    stats_footer,
    step_log,
    success,
    tool_use_badge,
    warning,
    welcome_banner,
)
from .printer import CliPrinter, EventRenderer

__all__ = [
    "AgentRunner",
    "AgentTUI",
    "BUILTIN_COMMANDS",
    "CliPrinter",
    "EventRenderer",
    "FileSaveHandler",
    "GuidelineProvider",
    "ISSUE_STYLES",
    "Mode",
    "PersonaProvider",
    "ROLE_STYLES",
    "RunResult",
    "SaveHandler",
    "SlashCommand",
    "TuiConfig",
    "TuiControls",
    "app_header",
    "chat_input_prompt",
    "chat_message",
    "error",
    "guideline_provider_from_library",
    "issue_line",
    "issues_block",
    "key_value_table",
    "persona_provider_from_library",
    "result_json",
    "result_markdown",
    "run_agent_tui",
    "section_rule",
    "stats_footer",
    "step_log",
    "success",
    "tool_use_badge",
    "warning",
    "welcome_banner",
]
